--
-- PostgreSQL database dump
--

-- Dumped from database version 16.1
-- Dumped by pg_dump version 16.1

-- Started on 2024-01-30 14:48:45

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4966 (class 1262 OID 16840)
-- Name: UrbanPlanning; Type: DATABASE; Schema: -; Owner: -
--

CREATE DATABASE "UrbanPlanning" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'Russian_Russia.1251';


\connect "UrbanPlanning"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA public;


--
-- TOC entry 4967 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 236 (class 1259 OID 16925)
-- Name: check; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."check" (
    id_check integer NOT NULL,
    date_of_the_sale timestamp without time zone NOT NULL,
    id_employee integer NOT NULL,
    id_client integer NOT NULL,
    is_estate_object integer NOT NULL
);


--
-- TOC entry 235 (class 1259 OID 16924)
-- Name: check_id_check_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."check" ALTER COLUMN id_check ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.check_id_check_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 16919)
-- Name: client; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.client (
    id_client integer NOT NULL,
    last_name character varying(50) NOT NULL,
    first_name character varying(50) NOT NULL,
    patronymic character varying(50) NOT NULL,
    birthday date NOT NULL,
    phone character(13) NOT NULL,
    is_legal_entity bit(1) NOT NULL,
    pasport_series character(4),
    pasport_number character(6),
    company_title character varying(50),
    "INN" character(10),
    "KPP" character(9),
    "OGRN" character(13),
    payment_account character(20),
    correspondent_account character(20),
    "BIK" character(13),
    id_gender integer
);


--
-- TOC entry 233 (class 1259 OID 16918)
-- Name: client_id_client_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.client ALTER COLUMN id_client ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.client_id_client_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 16907)
-- Name: employee; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.employee (
    id_employee integer NOT NULL,
    last_name character varying(50) NOT NULL,
    first_name character varying(50) NOT NULL,
    patronymic character varying(50) NOT NULL,
    birthday date NOT NULL,
    phone character(13) NOT NULL,
    pasport_series character(4) NOT NULL,
    pasport_number character(6) NOT NULL,
    login character varying(50) NOT NULL,
    password character varying(50) NOT NULL,
    id_post integer NOT NULL,
    id_gender integer NOT NULL
);


--
-- TOC entry 229 (class 1259 OID 16906)
-- Name: employee_id_employee_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.employee ALTER COLUMN id_employee ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employee_id_employee_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16854)
-- Name: estate_object; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.estate_object (
    id_estate_object integer NOT NULL,
    square numeric(14,4) NOT NULL,
    price numeric(12,2) NOT NULL,
    date_of_defenition timestamp without time zone NOT NULL,
    date_of_application timestamp without time zone NOT NULL,
    adress character varying(50) NOT NULL,
    id_layout_estate integer NOT NULL,
    id_postindex integer NOT NULL,
    id_type_of_activity integer NOT NULL,
    id_format integer NOT NULL
);


--
-- TOC entry 219 (class 1259 OID 16853)
-- Name: estate_object_id_estate_object_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.estate_object ALTER COLUMN id_estate_object ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.estate_object_id_estate_object_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 17052)
-- Name: estate_photo; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.estate_photo (
    id_estate_photo integer NOT NULL,
    photo_path character varying(500) NOT NULL,
    id_estate_object integer NOT NULL,
    id_employee integer NOT NULL
);


--
-- TOC entry 239 (class 1259 OID 17051)
-- Name: estate_photo_id_estate_photo_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.estate_photo ALTER COLUMN id_estate_photo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.estate_photo_id_estate_photo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 16846)
-- Name: estate_relation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.estate_relation (
    id_estate_relation integer NOT NULL,
    id_place_estate integer NOT NULL,
    id_buildiding_estate integer NOT NULL
);


--
-- TOC entry 217 (class 1259 OID 16845)
-- Name: estate_relation_id_estate_relation_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.estate_relation ALTER COLUMN id_estate_relation ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.estate_relation_id_estate_relation_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16860)
-- Name: flat_relation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.flat_relation (
    id_flat_relation integer NOT NULL,
    id_build_estate integer NOT NULL,
    id_flat_estate integer NOT NULL
);


--
-- TOC entry 221 (class 1259 OID 16859)
-- Name: flat_relation_id_flat_relation_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.flat_relation ALTER COLUMN id_flat_relation ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.flat_relation_id_flat_relation_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 16939)
-- Name: format; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.format (
    id_format integer NOT NULL,
    format_title character varying(50) NOT NULL
);


--
-- TOC entry 237 (class 1259 OID 16938)
-- Name: format_id_format_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.format ALTER COLUMN id_format ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.format_id_format_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 16913)
-- Name: gender; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.gender (
    id_gender integer NOT NULL,
    gender_title character varying(50) NOT NULL
);


--
-- TOC entry 231 (class 1259 OID 16912)
-- Name: gender_id_gender_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.gender ALTER COLUMN id_gender ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gender_id_gender_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16887)
-- Name: layout_estate; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.layout_estate (
    id_layout_estate integer NOT NULL,
    main_photo character varying(500) NOT NULL,
    id_employee integer NOT NULL
);


--
-- TOC entry 223 (class 1259 OID 16886)
-- Name: layout_estate_id_layout_estate_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.layout_estate ALTER COLUMN id_layout_estate ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.layout_estate_id_layout_estate_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16901)
-- Name: post; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.post (
    id_post integer NOT NULL,
    post_title character varying(50) NOT NULL
);


--
-- TOC entry 227 (class 1259 OID 16900)
-- Name: post_id_post_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.post ALTER COLUMN id_post ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.post_id_post_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16895)
-- Name: post_index; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.post_index (
    id_post_index integer NOT NULL,
    post_index_value character(6) NOT NULL
);


--
-- TOC entry 225 (class 1259 OID 16894)
-- Name: post_index_id_post_index_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.post_index ALTER COLUMN id_post_index ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.post_index_id_post_index_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 16842)
-- Name: type_of_activity; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.type_of_activity (
    id_type_of_activity integer NOT NULL,
    title integer NOT NULL
);


--
-- TOC entry 215 (class 1259 OID 16841)
-- Name: type_of_activity_id_type_of_activity_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.type_of_activity ALTER COLUMN id_type_of_activity ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.type_of_activity_id_type_of_activity_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4956 (class 0 OID 16925)
-- Dependencies: 236
-- Data for Name: check; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4954 (class 0 OID 16919)
-- Dependencies: 234
-- Data for Name: client; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4950 (class 0 OID 16907)
-- Dependencies: 230
-- Data for Name: employee; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4940 (class 0 OID 16854)
-- Dependencies: 220
-- Data for Name: estate_object; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4960 (class 0 OID 17052)
-- Dependencies: 240
-- Data for Name: estate_photo; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4938 (class 0 OID 16846)
-- Dependencies: 218
-- Data for Name: estate_relation; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4942 (class 0 OID 16860)
-- Dependencies: 222
-- Data for Name: flat_relation; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4958 (class 0 OID 16939)
-- Dependencies: 238
-- Data for Name: format; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4952 (class 0 OID 16913)
-- Dependencies: 232
-- Data for Name: gender; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4944 (class 0 OID 16887)
-- Dependencies: 224
-- Data for Name: layout_estate; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4948 (class 0 OID 16901)
-- Dependencies: 228
-- Data for Name: post; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4946 (class 0 OID 16895)
-- Dependencies: 226
-- Data for Name: post_index; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4936 (class 0 OID 16842)
-- Dependencies: 216
-- Data for Name: type_of_activity; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4968 (class 0 OID 0)
-- Dependencies: 235
-- Name: check_id_check_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.check_id_check_seq', 1, false);


--
-- TOC entry 4969 (class 0 OID 0)
-- Dependencies: 233
-- Name: client_id_client_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.client_id_client_seq', 1, false);


--
-- TOC entry 4970 (class 0 OID 0)
-- Dependencies: 229
-- Name: employee_id_employee_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.employee_id_employee_seq', 1, false);


--
-- TOC entry 4971 (class 0 OID 0)
-- Dependencies: 219
-- Name: estate_object_id_estate_object_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.estate_object_id_estate_object_seq', 1, false);


--
-- TOC entry 4972 (class 0 OID 0)
-- Dependencies: 239
-- Name: estate_photo_id_estate_photo_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.estate_photo_id_estate_photo_seq', 1, false);


--
-- TOC entry 4973 (class 0 OID 0)
-- Dependencies: 217
-- Name: estate_relation_id_estate_relation_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.estate_relation_id_estate_relation_seq', 1, false);


--
-- TOC entry 4974 (class 0 OID 0)
-- Dependencies: 221
-- Name: flat_relation_id_flat_relation_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.flat_relation_id_flat_relation_seq', 1, false);


--
-- TOC entry 4975 (class 0 OID 0)
-- Dependencies: 237
-- Name: format_id_format_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.format_id_format_seq', 1, false);


--
-- TOC entry 4976 (class 0 OID 0)
-- Dependencies: 231
-- Name: gender_id_gender_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.gender_id_gender_seq', 1, false);


--
-- TOC entry 4977 (class 0 OID 0)
-- Dependencies: 223
-- Name: layout_estate_id_layout_estate_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.layout_estate_id_layout_estate_seq', 1, false);


--
-- TOC entry 4978 (class 0 OID 0)
-- Dependencies: 227
-- Name: post_id_post_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.post_id_post_seq', 1, false);


--
-- TOC entry 4979 (class 0 OID 0)
-- Dependencies: 225
-- Name: post_index_id_post_index_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.post_index_id_post_index_seq', 1, false);


--
-- TOC entry 4980 (class 0 OID 0)
-- Dependencies: 215
-- Name: type_of_activity_id_type_of_activity_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.type_of_activity_id_type_of_activity_seq', 1, false);


--
-- TOC entry 4770 (class 2606 OID 16929)
-- Name: check check_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."check"
    ADD CONSTRAINT check_pk PRIMARY KEY (id_check);


--
-- TOC entry 4768 (class 2606 OID 16923)
-- Name: client client_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.client
    ADD CONSTRAINT client_pk PRIMARY KEY (id_client);


--
-- TOC entry 4764 (class 2606 OID 16911)
-- Name: employee employee_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee
    ADD CONSTRAINT employee_pk PRIMARY KEY (id_employee);


--
-- TOC entry 4754 (class 2606 OID 16858)
-- Name: estate_object estate_object_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estate_object
    ADD CONSTRAINT estate_object_pk PRIMARY KEY (id_estate_object);


--
-- TOC entry 4774 (class 2606 OID 17056)
-- Name: estate_photo estate_photo_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estate_photo
    ADD CONSTRAINT estate_photo_pk PRIMARY KEY (id_estate_photo);


--
-- TOC entry 4752 (class 2606 OID 16850)
-- Name: estate_relation estate_relation_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estate_relation
    ADD CONSTRAINT estate_relation_pk PRIMARY KEY (id_estate_relation);


--
-- TOC entry 4756 (class 2606 OID 16864)
-- Name: flat_relation flat_relation_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flat_relation
    ADD CONSTRAINT flat_relation_pk PRIMARY KEY (id_flat_relation);


--
-- TOC entry 4772 (class 2606 OID 16943)
-- Name: format format_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.format
    ADD CONSTRAINT format_pk PRIMARY KEY (id_format);


--
-- TOC entry 4766 (class 2606 OID 16917)
-- Name: gender gender_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.gender
    ADD CONSTRAINT gender_pk PRIMARY KEY (id_gender);


--
-- TOC entry 4758 (class 2606 OID 16893)
-- Name: layout_estate layout_estate_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.layout_estate
    ADD CONSTRAINT layout_estate_pk PRIMARY KEY (id_layout_estate);


--
-- TOC entry 4760 (class 2606 OID 16899)
-- Name: post_index post_index_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_index
    ADD CONSTRAINT post_index_pk PRIMARY KEY (id_post_index);


--
-- TOC entry 4762 (class 2606 OID 16905)
-- Name: post post_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post
    ADD CONSTRAINT post_pk PRIMARY KEY (id_post);


--
-- TOC entry 4750 (class 2606 OID 16852)
-- Name: type_of_activity type_of_activity_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.type_of_activity
    ADD CONSTRAINT type_of_activity_pk PRIMARY KEY (id_type_of_activity);


--
-- TOC entry 4787 (class 2606 OID 17025)
-- Name: check check_client_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."check"
    ADD CONSTRAINT check_client_fk FOREIGN KEY (id_client) REFERENCES public.client(id_client);


--
-- TOC entry 4788 (class 2606 OID 17030)
-- Name: check check_employee_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."check"
    ADD CONSTRAINT check_employee_fk FOREIGN KEY (id_employee) REFERENCES public.employee(id_employee);


--
-- TOC entry 4789 (class 2606 OID 17046)
-- Name: check check_estate_object_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."check"
    ADD CONSTRAINT check_estate_object_fk FOREIGN KEY (is_estate_object) REFERENCES public.estate_object(id_estate_object);


--
-- TOC entry 4786 (class 2606 OID 17010)
-- Name: client client_gender_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.client
    ADD CONSTRAINT client_gender_fk FOREIGN KEY (id_gender) REFERENCES public.gender(id_gender);


--
-- TOC entry 4784 (class 2606 OID 17020)
-- Name: employee employee_gender_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee
    ADD CONSTRAINT employee_gender_fk FOREIGN KEY (id_gender) REFERENCES public.gender(id_gender);


--
-- TOC entry 4785 (class 2606 OID 17015)
-- Name: employee employee_post_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee
    ADD CONSTRAINT employee_post_fk FOREIGN KEY (id_post) REFERENCES public.post(id_post);


--
-- TOC entry 4777 (class 2606 OID 16965)
-- Name: estate_object estate_object_format_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estate_object
    ADD CONSTRAINT estate_object_format_fk FOREIGN KEY (id_format) REFERENCES public.format(id_format);


--
-- TOC entry 4778 (class 2606 OID 16970)
-- Name: estate_object estate_object_layout_estate_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estate_object
    ADD CONSTRAINT estate_object_layout_estate_fk FOREIGN KEY (id_layout_estate) REFERENCES public.layout_estate(id_layout_estate);


--
-- TOC entry 4779 (class 2606 OID 16955)
-- Name: estate_object estate_object_post_index_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estate_object
    ADD CONSTRAINT estate_object_post_index_fk FOREIGN KEY (id_postindex) REFERENCES public.post_index(id_post_index);


--
-- TOC entry 4780 (class 2606 OID 16960)
-- Name: estate_object estate_object_type_of_activity_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estate_object
    ADD CONSTRAINT estate_object_type_of_activity_fk FOREIGN KEY (id_type_of_activity) REFERENCES public.type_of_activity(id_type_of_activity);


--
-- TOC entry 4790 (class 2606 OID 17070)
-- Name: estate_photo estate_photo_employee_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estate_photo
    ADD CONSTRAINT estate_photo_employee_fk FOREIGN KEY (id_employee) REFERENCES public.employee(id_employee);


--
-- TOC entry 4791 (class 2606 OID 17059)
-- Name: estate_photo estate_photo_estate_object_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estate_photo
    ADD CONSTRAINT estate_photo_estate_object_fk FOREIGN KEY (id_estate_object) REFERENCES public.estate_object(id_estate_object);


--
-- TOC entry 4775 (class 2606 OID 16985)
-- Name: estate_relation estate_relation_estate_object_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estate_relation
    ADD CONSTRAINT estate_relation_estate_object_fk FOREIGN KEY (id_place_estate) REFERENCES public.estate_object(id_estate_object);


--
-- TOC entry 4776 (class 2606 OID 16990)
-- Name: estate_relation estate_relation_estate_object_fk_1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estate_relation
    ADD CONSTRAINT estate_relation_estate_object_fk_1 FOREIGN KEY (id_buildiding_estate) REFERENCES public.estate_object(id_estate_object);


--
-- TOC entry 4781 (class 2606 OID 16975)
-- Name: flat_relation flat_relation_estate_object_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flat_relation
    ADD CONSTRAINT flat_relation_estate_object_fk FOREIGN KEY (id_build_estate) REFERENCES public.estate_object(id_estate_object);


--
-- TOC entry 4782 (class 2606 OID 16980)
-- Name: flat_relation flat_relation_estate_object_fk_1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flat_relation
    ADD CONSTRAINT flat_relation_estate_object_fk_1 FOREIGN KEY (id_flat_estate) REFERENCES public.estate_object(id_estate_object);


--
-- TOC entry 4783 (class 2606 OID 17005)
-- Name: layout_estate layout_estate_employee_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.layout_estate
    ADD CONSTRAINT layout_estate_employee_fk FOREIGN KEY (id_employee) REFERENCES public.employee(id_employee);


-- Completed on 2024-01-30 14:48:45

--
-- PostgreSQL database dump complete
--

